baseURL = 'https://jerryuhoo.github.io/'
languageCode = 'en-us'
title = 'Wings Music'
theme = 'digitalgarden'

[menu]
[[menu.main]]
  name = 'Home'
  url = '/'
  weight = 1
[[menu.main]]
  name = 'Content'
  params.header = true
  weight = 2
[[menu.main]]
  name = 'Articles'
  url = '/articles'
  weight = 3
[[menu.main]]
  name = 'Projects'
  url = '/portfolio'
  weight = 4
[[menu.main]]
  name = 'Stack'
  url = '/stack'
  weight = 5

[[menu.social]]
  name = 'GitHub'
  url = 'https://github.com/jerryuhoo'
  weight = 1
[[menu.social]]
  name = 'LinkedIn'
  url = 'https://www.linkedin.com/in/yifengyu/'
  weight = 2
[[menu.social]]
  name = 'Instagram'
  url = 'https://www.instagram.com/wingsmus/'
  weight = 3
[[menu.social]]
  name = 'Email'
  url = 'mailto:jerryuhoo@gmail.com'
  weight = 4
